# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
