# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_type', '0001_initial'),
        ('event', '0004_auto_20180110_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='event_types',
            field=models.ManyToManyField(blank=True, related_name='event_types', to='event_type.EventType'),
        ),
    ]
