# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180110_0834'),
        ('main', '0009_token'),
    ]

    operations = [
    ]
