# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-13 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180119_0347'),
        ('main', '0010_merge_20180119_2350'),
    ]

    operations = [
    ]
