# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180212_2213'),
        ('officer', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='category',
        ),
        migrations.RemoveField(
            model_name='org',
            name='tags',
        ),
        migrations.AddField(
            model_name='org',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='category.Category'),
        ),
        migrations.AddField(
            model_name='org',
            name='officers',
            field=models.ManyToManyField(related_name='officers', to='officer.Officer'),
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
